# Only build tags
if: tag IS present
sudo: required
language: shell

script:
  - echo "CI TEST" > release_file

after_script:
  - export RELEASE_FILE="release-$(git describe --tag --abbrev=0)"

deploy:
  provider: releases
  api_key: $DEPLOY_TOKEN
  file_glob: true
  file:
    - $RELEASE_FILE
  skip_cleanup: true
  on:
    tags: true
